### SELECT Busca a informação dos reviews
GET  http://localhost:3001/ratings/ HTTP/1.1

### SELECT Busca review pelo seu id
GET  http://localhost:3001/ratings/:rating_id HTTP/1.1

### SELECT Busca reviews para um jogo
GET  http://localhost:3001/ratings?game_id=5fc2e86e9ab508004976383b HTTP/1.1

### INSERT Registra review ((*) Campos obrigatórios)
POST  http://localhost:3001/ratings HTTP/1.1
Content-Type: application/json

{
    "rate": 10,
    "comment": "Esse game é incrível",
    "game_id": "5fc2e86e9ab508004976383b"
}

### UPDATE
PUT  http://localhost:3001/ratings/:rating_id HTTP/1.1
Content-Type: application/json

{
    "rate": 8
}

### DELETE Remove o review
DELETE  http://localhost:3001/ratings/:rating_id HTTP/1.1